// DRIVER_LCD
// SEPTEMBER 30, 2025

#ifndef _DRIVER_LCD_
#define _DRIVER_LCD_

#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdbool.h>

#include "util_dataqueue.h"

#define DRIVER_LCD_LVGL_TICK_PERIOD_MS      (2)
#define DRIVER_LCD_LVGL_TASK_PERIOD_MS      (50)

#define DRIVER_LCD_DISPLAY_HRES             (240)
#define DRIVER_LCD_DISPLAY_VRES             (320)

#define DRIVER_LCD_DATAQUEUE_MAX            (16)

#define DRIVER_LCD_SPI_HOST                 SPI3_HOST
#define DRIVER_LCD_SPI_CLK_HZ               (80 * 1000 * 1000)

#define DRIVER_LCD_LEDC_TIMER               LEDC_TIMER_0
#define DRIVER_LCD_LEDC_MODE                LEDC_LOW_SPEED_MODE
#define DRIVER_LCD_LEDC_CHANNEL             LEDC_CHANNEL_0
#define DRIVER_LCD_LEDC_RESOLUTION          LEDC_TIMER_13_BIT
#define DRIVER_LCD_LEDC_FREQ_HZ             (5000)
#define DRIVER_LCD_LEDC_DUTY_MAX            ((1 << DRIVER_LCD_LEDC_RESOLUTION) - 1)

typedef enum {
    DRIVER_LCD_COMMAND_DEMO = 0,
    DRIVER_LCD_COMMAND_LOAD_UI_SCREEN,
    DRIVER_LCD_COMMAND_REFRESH_UI,
    DRIVER_LCD_COMMAND_SET_SCREEN2_MESSAGE,
    DRIVER_LCD_COMMAND_SET_SCREEN1_MESSAGE_STATUS,
    DRIVER_LCD_COMMAND_SET_SCREEN1_PANEL_STATUS_COLOR,
    DRIVER_LCD_COMMAND_SET_SCREEN1_PRINTERDATA_VISIBLE,
    DRIVER_LCD_COMMAND_SET_SCREEN1_LABEL_MODE,
    DRIVER_LCD_COMMAND_SET_SCREEN1_LABEL_BED_TEMP_ACTUAL,
    DRIVER_LCD_COMMAND_SET_SCREEN1_LABEL_BED_TEMP_TARGET,
    DRIVER_LCD_COMMAND_SET_SCREEN1_LABEL_NOZZLE_TEMP_ACTUAL,
    DRIVER_LCD_COMMAND_SET_SCREEN1_LABEL_NOZZLE_TEMP_TARGET,
}driver_lcd_command_type_t;

typedef enum {
    DRIVER_LCD_SCREEN_STARTUP = 0,
    DRIVER_LCD_SCREEN_HOME
}driver_lcd_screen_type_t;

typedef enum {
    DRIVER_LCD_STATUS_COLOR_GREEN = 0,
    DRIVER_LCD_STATUS_COLOR_RED,
}driver_lcd_status_color_t;

bool DRIVER_LCD_Init(void);

bool DRIVER_LCD_AddCommand(util_dataqueue_item_t* dq_i);

#endif