// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: project_ui

#ifndef _PROJECT_UI_UI_H
#define _PROJECT_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Screen2.h"
#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_icon_3dprinter_png);   // assets/icon_3dprinter.png
LV_IMG_DECLARE( ui_img_icon_heat_png);   // assets/icon_heat.png
LV_IMG_DECLARE( ui_img_icon_nozzle_png);   // assets/icon_nozzle.png
LV_IMG_DECLARE( ui_img_icon_percent_png);   // assets/icon_percent.png
LV_IMG_DECLARE( ui_img_icon_layers_png);   // assets/icon_layers.png
LV_IMG_DECLARE( ui_img_icon_clock_png);   // assets/icon_clock.png
LV_IMG_DECLARE( ui_img_icon_printer_png);   // assets/icon_printer.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
