// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: project_ui

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Container1 = NULL;lv_obj_t *ui_PanelHEADER = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_Panel9 = NULL;lv_obj_t *ui_Sceen1PanelSTATUS = NULL;lv_obj_t *ui_Screen1LabelSTATUS = NULL;lv_obj_t *ui_ContainerPRINTERDATA = NULL;lv_obj_t *ui_PanelBEDTEMP = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_Container2 = NULL;lv_obj_t *ui_Container3 = NULL;lv_obj_t *ui_Screen1LabelBEDTEMPACTUAL = NULL;lv_obj_t *ui_Screen1LabelBEDTEMPTARGET = NULL;lv_obj_t *ui_Container4 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_PanelNOZZLETEMP = NULL;lv_obj_t *ui_Image2 = NULL;lv_obj_t *ui_Label8 = NULL;lv_obj_t *ui_Container5 = NULL;lv_obj_t *ui_Container6 = NULL;lv_obj_t *ui_Screen1LabelNOZZLETEMPACTUAL = NULL;lv_obj_t *ui_Screen1LabelNOZZLETEMPTARGET = NULL;lv_obj_t *ui_Container7 = NULL;lv_obj_t *ui_Label11 = NULL;lv_obj_t *ui_Label12 = NULL;lv_obj_t *ui_PanelPRINTPROGRESS = NULL;lv_obj_t *ui_Image5 = NULL;lv_obj_t *ui_Label13 = NULL;lv_obj_t *ui_Container8 = NULL;lv_obj_t *ui_Screen1BarPRINTPROGRESS = NULL;lv_obj_t *ui_Screen1LabelPrintProgress = NULL;lv_obj_t *ui_PanelLAYER = NULL;lv_obj_t *ui_Image4 = NULL;lv_obj_t *ui_Label15 = NULL;lv_obj_t *ui_Container9 = NULL;lv_obj_t *ui_Container10 = NULL;lv_obj_t *ui_Screen1LabelLAYERCURRENT = NULL;lv_obj_t *ui_Screen1LabelLAYERTOTAL = NULL;lv_obj_t *ui_Container11 = NULL;lv_obj_t *ui_Label18 = NULL;lv_obj_t *ui_Label19 = NULL;lv_obj_t *ui_PanelTIME = NULL;lv_obj_t *ui_Image6 = NULL;lv_obj_t *ui_Label20 = NULL;lv_obj_t *ui_Container12 = NULL;lv_obj_t *ui_Screen1LabelTIMEREMAINING = NULL;lv_obj_t *ui_Label22 = NULL;lv_obj_t *ui_PanelPRINTER = NULL;lv_obj_t *ui_Panel3 = NULL;lv_obj_t *ui_Image7 = NULL;lv_obj_t *ui_Screen1LabelMODE = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container1 = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, lv_pct(100));
lv_obj_set_height( ui_Container1, lv_pct(100));
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelHEADER = lv_obj_create(ui_Container1);
lv_obj_set_width( ui_PanelHEADER, lv_pct(100));
lv_obj_set_height( ui_PanelHEADER, LV_SIZE_CONTENT);   /// 53
lv_obj_set_align( ui_PanelHEADER, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelHEADER,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PanelHEADER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_PanelHEADER, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelHEADER, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelHEADER, lv_color_hex(0x0B0F14), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelHEADER, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelHEADER, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelHEADER, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PanelHEADER, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_PanelHEADER, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PanelHEADER, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelHEADER, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelHEADER, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelHEADER, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_PanelHEADER);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"PRINTER STATUS");
lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel9 = lv_obj_create(ui_PanelHEADER);
lv_obj_set_width( ui_Panel9, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Panel9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Panel9, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel9,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Panel9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Panel9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Panel9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Panel9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Panel9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Panel9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Panel9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sceen1PanelSTATUS = lv_obj_create(ui_Panel9);
lv_obj_set_width( ui_Sceen1PanelSTATUS, 10);
lv_obj_set_height( ui_Sceen1PanelSTATUS, 10);
lv_obj_set_align( ui_Sceen1PanelSTATUS, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Sceen1PanelSTATUS, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Sceen1PanelSTATUS, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Sceen1PanelSTATUS, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Sceen1PanelSTATUS, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Sceen1PanelSTATUS, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Sceen1PanelSTATUS, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Sceen1PanelSTATUS, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Sceen1PanelSTATUS, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1LabelSTATUS = lv_label_create(ui_Panel9);
lv_obj_set_width( ui_Screen1LabelSTATUS, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Screen1LabelSTATUS, LV_SIZE_CONTENT);   /// 100
lv_obj_set_align( ui_Screen1LabelSTATUS, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1LabelSTATUS,"OFFLINE");
lv_obj_set_style_text_color(ui_Screen1LabelSTATUS, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1LabelSTATUS, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1LabelSTATUS, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContainerPRINTERDATA = lv_obj_create(ui_Container1);
lv_obj_remove_style_all(ui_ContainerPRINTERDATA);
lv_obj_set_width( ui_ContainerPRINTERDATA, lv_pct(100));
lv_obj_set_flex_grow( ui_ContainerPRINTERDATA, 1);
lv_obj_set_flex_flow(ui_ContainerPRINTERDATA,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_ContainerPRINTERDATA, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_ContainerPRINTERDATA, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ContainerPRINTERDATA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ContainerPRINTERDATA, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelBEDTEMP = lv_obj_create(ui_ContainerPRINTERDATA);
lv_obj_set_height( ui_PanelBEDTEMP, 48);
lv_obj_set_width( ui_PanelBEDTEMP, lv_pct(100));
lv_obj_set_align( ui_PanelBEDTEMP, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelBEDTEMP,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PanelBEDTEMP, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_PanelBEDTEMP, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelBEDTEMP, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelBEDTEMP, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelBEDTEMP, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelBEDTEMP, lv_color_hex(0x0B0F14), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelBEDTEMP, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PanelBEDTEMP, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PanelBEDTEMP, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelBEDTEMP, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelBEDTEMP, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelBEDTEMP, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_image_create(ui_PanelBEDTEMP);
lv_image_set_src(ui_Image1, &ui_img_icon_heat_png);
lv_obj_set_width( ui_Image1, 36);
lv_obj_set_height( ui_Image1, lv_pct(100));
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image1,200);
lv_obj_set_style_border_width(ui_Image1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Image1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Image1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Image1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Image1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_PanelBEDTEMP);
lv_obj_set_height( ui_Label3, lv_pct(100));
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 100
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"\nBED\nTEMP    ");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container2 = lv_obj_create(ui_PanelBEDTEMP);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_height( ui_Container2, lv_pct(100));
lv_obj_set_flex_grow( ui_Container2, 1);
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container3 = lv_obj_create(ui_Container2);
lv_obj_remove_style_all(ui_Container3);
lv_obj_set_width( ui_Container3, lv_pct(100));
lv_obj_set_height( ui_Container3, LV_SIZE_CONTENT);   /// 100
lv_obj_set_align( ui_Container3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_set_style_border_width(ui_Container3, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Container3, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container3, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container3, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container3, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Screen1LabelBEDTEMPACTUAL = lv_label_create(ui_Container3);
lv_obj_set_width( ui_Screen1LabelBEDTEMPACTUAL, lv_pct(50));
lv_obj_set_height( ui_Screen1LabelBEDTEMPACTUAL, LV_SIZE_CONTENT);   /// 100
lv_obj_set_align( ui_Screen1LabelBEDTEMPACTUAL, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1LabelBEDTEMPACTUAL,"");
lv_obj_set_style_text_color(ui_Screen1LabelBEDTEMPACTUAL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1LabelBEDTEMPACTUAL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Screen1LabelBEDTEMPACTUAL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_Screen1LabelBEDTEMPACTUAL, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1LabelBEDTEMPACTUAL, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1LabelBEDTEMPTARGET = lv_label_create(ui_Container3);
lv_obj_set_width( ui_Screen1LabelBEDTEMPTARGET, lv_pct(50));
lv_obj_set_height( ui_Screen1LabelBEDTEMPTARGET, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Screen1LabelBEDTEMPTARGET, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1LabelBEDTEMPTARGET,"");
lv_obj_set_style_text_color(ui_Screen1LabelBEDTEMPTARGET, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1LabelBEDTEMPTARGET, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Screen1LabelBEDTEMPTARGET, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_Screen1LabelBEDTEMPTARGET, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1LabelBEDTEMPTARGET, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container4 = lv_obj_create(ui_Container2);
lv_obj_remove_style_all(ui_Container4);
lv_obj_set_width( ui_Container4, lv_pct(100));
lv_obj_set_height( ui_Container4, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Container4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container4,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container4, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_width(ui_Container4, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Container4, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container4, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container4, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container4, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Container4);
lv_obj_set_width( ui_Label1, lv_pct(50));
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"ACTUAL");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFF7830), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label1, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_Label1, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Label1, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Label1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Label1, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_Container4);
lv_obj_set_width( ui_Label6, lv_pct(50));
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"TARGET");
lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_Label6, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelNOZZLETEMP = lv_obj_create(ui_ContainerPRINTERDATA);
lv_obj_set_height( ui_PanelNOZZLETEMP, 48);
lv_obj_set_width( ui_PanelNOZZLETEMP, lv_pct(100));
lv_obj_set_align( ui_PanelNOZZLETEMP, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelNOZZLETEMP,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PanelNOZZLETEMP, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_PanelNOZZLETEMP, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelNOZZLETEMP, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelNOZZLETEMP, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelNOZZLETEMP, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelNOZZLETEMP, lv_color_hex(0x0B0F14), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelNOZZLETEMP, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PanelNOZZLETEMP, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PanelNOZZLETEMP, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelNOZZLETEMP, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelNOZZLETEMP, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelNOZZLETEMP, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image2 = lv_image_create(ui_PanelNOZZLETEMP);
lv_image_set_src(ui_Image2, &ui_img_icon_nozzle_png);
lv_obj_set_width( ui_Image2, 36);
lv_obj_set_height( ui_Image2, 36);
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_inner_align( ui_Image2, LV_IMAGE_ALIGN_TILE );
lv_obj_set_style_border_width(ui_Image2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Image2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Image2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Image2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Image2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_PanelNOZZLETEMP);
lv_obj_set_height( ui_Label8, lv_pct(100));
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 100
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"\nNOZZLE\nTEMP ");
lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container5 = lv_obj_create(ui_PanelNOZZLETEMP);
lv_obj_remove_style_all(ui_Container5);
lv_obj_set_height( ui_Container5, lv_pct(100));
lv_obj_set_flex_grow( ui_Container5, 1);
lv_obj_set_align( ui_Container5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container5,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container6 = lv_obj_create(ui_Container5);
lv_obj_remove_style_all(ui_Container6);
lv_obj_set_width( ui_Container6, lv_pct(100));
lv_obj_set_height( ui_Container6, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Container6, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container6,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_set_style_border_width(ui_Container6, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Container6, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container6, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container6, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container6, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Screen1LabelNOZZLETEMPACTUAL = lv_label_create(ui_Container6);
lv_obj_set_width( ui_Screen1LabelNOZZLETEMPACTUAL, lv_pct(50));
lv_obj_set_height( ui_Screen1LabelNOZZLETEMPACTUAL, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Screen1LabelNOZZLETEMPACTUAL, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1LabelNOZZLETEMPACTUAL,"");
lv_obj_set_style_text_color(ui_Screen1LabelNOZZLETEMPACTUAL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1LabelNOZZLETEMPACTUAL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Screen1LabelNOZZLETEMPACTUAL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_Screen1LabelNOZZLETEMPACTUAL, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1LabelNOZZLETEMPACTUAL, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1LabelNOZZLETEMPTARGET = lv_label_create(ui_Container6);
lv_obj_set_width( ui_Screen1LabelNOZZLETEMPTARGET, lv_pct(50));
lv_obj_set_height( ui_Screen1LabelNOZZLETEMPTARGET, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Screen1LabelNOZZLETEMPTARGET, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1LabelNOZZLETEMPTARGET,"");
lv_obj_set_style_text_color(ui_Screen1LabelNOZZLETEMPTARGET, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1LabelNOZZLETEMPTARGET, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Screen1LabelNOZZLETEMPTARGET, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_Screen1LabelNOZZLETEMPTARGET, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1LabelNOZZLETEMPTARGET, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container7 = lv_obj_create(ui_Container5);
lv_obj_remove_style_all(ui_Container7);
lv_obj_set_width( ui_Container7, lv_pct(100));
lv_obj_set_height( ui_Container7, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Container7, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container7,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container7, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_width(ui_Container7, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Container7, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container7, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container7, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container7, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Label11 = lv_label_create(ui_Container7);
lv_obj_set_width( ui_Label11, lv_pct(50));
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"ACTUAL");
lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x00C8E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label11, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_Label11, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Label11, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Label11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Label11, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Label11, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label12 = lv_label_create(ui_Container7);
lv_obj_set_width( ui_Label12, lv_pct(50));
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"TARGET");
lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label12, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_Label12, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelPRINTPROGRESS = lv_obj_create(ui_ContainerPRINTERDATA);
lv_obj_set_height( ui_PanelPRINTPROGRESS, 48);
lv_obj_set_width( ui_PanelPRINTPROGRESS, lv_pct(100));
lv_obj_set_align( ui_PanelPRINTPROGRESS, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelPRINTPROGRESS,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PanelPRINTPROGRESS, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_PanelPRINTPROGRESS, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelPRINTPROGRESS, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelPRINTPROGRESS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelPRINTPROGRESS, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelPRINTPROGRESS, lv_color_hex(0x0B0F14), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelPRINTPROGRESS, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PanelPRINTPROGRESS, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PanelPRINTPROGRESS, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelPRINTPROGRESS, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelPRINTPROGRESS, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelPRINTPROGRESS, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image5 = lv_image_create(ui_PanelPRINTPROGRESS);
lv_image_set_src(ui_Image5, &ui_img_icon_percent_png);
lv_obj_set_width( ui_Image5, 36);
lv_obj_set_height( ui_Image5, 36);
lv_obj_set_align( ui_Image5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image5,200);
lv_obj_set_style_border_width(ui_Image5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Image5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Image5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Image5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Image5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label13 = lv_label_create(ui_PanelPRINTPROGRESS);
lv_obj_set_height( ui_Label13, lv_pct(100));
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 100
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"\nPRINT\nPROGRESS");
lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label13, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container8 = lv_obj_create(ui_PanelPRINTPROGRESS);
lv_obj_remove_style_all(ui_Container8);
lv_obj_set_height( ui_Container8, lv_pct(100));
lv_obj_set_flex_grow( ui_Container8, 1);
lv_obj_set_align( ui_Container8, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container8,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1BarPRINTPROGRESS = lv_bar_create(ui_Container8);
lv_obj_set_height( ui_Screen1BarPRINTPROGRESS, 14);
lv_obj_set_width( ui_Screen1BarPRINTPROGRESS, lv_pct(95));
lv_obj_set_align( ui_Screen1BarPRINTPROGRESS, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Screen1BarPRINTPROGRESS, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Screen1BarPRINTPROGRESS, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1BarPRINTPROGRESS, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Screen1BarPRINTPROGRESS, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Screen1BarPRINTPROGRESS, lv_color_hex(0x38DE78), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1BarPRINTPROGRESS, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_Screen1BarPRINTPROGRESS,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_Screen1BarPRINTPROGRESS, lv_obj_get_style_pad_right(ui_Screen1BarPRINTPROGRESS,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_Screen1LabelPrintProgress = lv_label_create(ui_Container8);
lv_obj_set_width( ui_Screen1LabelPrintProgress, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Screen1LabelPrintProgress, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Screen1LabelPrintProgress, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1LabelPrintProgress,"% COMPLETE");
lv_obj_set_style_text_color(ui_Screen1LabelPrintProgress, lv_color_hex(0x38DE78), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1LabelPrintProgress, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1LabelPrintProgress, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Screen1LabelPrintProgress, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Screen1LabelPrintProgress, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Screen1LabelPrintProgress, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Screen1LabelPrintProgress, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelLAYER = lv_obj_create(ui_ContainerPRINTERDATA);
lv_obj_set_height( ui_PanelLAYER, 48);
lv_obj_set_width( ui_PanelLAYER, lv_pct(100));
lv_obj_set_align( ui_PanelLAYER, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelLAYER,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PanelLAYER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_PanelLAYER, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelLAYER, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelLAYER, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelLAYER, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelLAYER, lv_color_hex(0x0B0F14), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelLAYER, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PanelLAYER, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PanelLAYER, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelLAYER, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelLAYER, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelLAYER, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image4 = lv_image_create(ui_PanelLAYER);
lv_image_set_src(ui_Image4, &ui_img_icon_layers_png);
lv_obj_set_width( ui_Image4, 36);
lv_obj_set_height( ui_Image4, 36);
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image4,220);
lv_obj_set_style_border_width(ui_Image4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Image4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Image4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Image4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Image4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label15 = lv_label_create(ui_PanelLAYER);
lv_obj_set_height( ui_Label15, lv_pct(100));
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 100
lv_obj_set_align( ui_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label15,"\nLAYER");
lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container9 = lv_obj_create(ui_PanelLAYER);
lv_obj_remove_style_all(ui_Container9);
lv_obj_set_height( ui_Container9, lv_pct(100));
lv_obj_set_flex_grow( ui_Container9, 1);
lv_obj_set_align( ui_Container9, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container9,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container10 = lv_obj_create(ui_Container9);
lv_obj_remove_style_all(ui_Container10);
lv_obj_set_width( ui_Container10, lv_pct(100));
lv_obj_set_height( ui_Container10, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Container10, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container10,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_set_style_border_width(ui_Container10, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Container10, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container10, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container10, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container10, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Screen1LabelLAYERCURRENT = lv_label_create(ui_Container10);
lv_obj_set_width( ui_Screen1LabelLAYERCURRENT, lv_pct(50));
lv_obj_set_height( ui_Screen1LabelLAYERCURRENT, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Screen1LabelLAYERCURRENT, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1LabelLAYERCURRENT,"");
lv_obj_set_style_text_color(ui_Screen1LabelLAYERCURRENT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1LabelLAYERCURRENT, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Screen1LabelLAYERCURRENT, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_Screen1LabelLAYERCURRENT, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1LabelLAYERCURRENT, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1LabelLAYERTOTAL = lv_label_create(ui_Container10);
lv_obj_set_width( ui_Screen1LabelLAYERTOTAL, lv_pct(50));
lv_obj_set_height( ui_Screen1LabelLAYERTOTAL, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Screen1LabelLAYERTOTAL, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1LabelLAYERTOTAL,"");
lv_obj_set_style_text_color(ui_Screen1LabelLAYERTOTAL, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1LabelLAYERTOTAL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Screen1LabelLAYERTOTAL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_Screen1LabelLAYERTOTAL, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1LabelLAYERTOTAL, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container11 = lv_obj_create(ui_Container9);
lv_obj_remove_style_all(ui_Container11);
lv_obj_set_width( ui_Container11, lv_pct(100));
lv_obj_set_height( ui_Container11, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Container11, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container11,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container11, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container11, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_width(ui_Container11, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Container11, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container11, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container11, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container11, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Label18 = lv_label_create(ui_Container11);
lv_obj_set_width( ui_Label18, lv_pct(50));
lv_obj_set_height( ui_Label18, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Label18, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label18,"CURRENT");
lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xA040F0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label18, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label18, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label18, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_Label18, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Label18, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Label18, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Label18, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Label18, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label19 = lv_label_create(ui_Container11);
lv_obj_set_width( ui_Label19, lv_pct(50));
lv_obj_set_height( ui_Label19, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Label19, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label19,"TOTAL");
lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label19, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_Label19, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelTIME = lv_obj_create(ui_ContainerPRINTERDATA);
lv_obj_set_height( ui_PanelTIME, 48);
lv_obj_set_width( ui_PanelTIME, lv_pct(100));
lv_obj_set_align( ui_PanelTIME, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelTIME,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PanelTIME, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_PanelTIME, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelTIME, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelTIME, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelTIME, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelTIME, lv_color_hex(0x0B0F14), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelTIME, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PanelTIME, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PanelTIME, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelTIME, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelTIME, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelTIME, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image6 = lv_image_create(ui_PanelTIME);
lv_image_set_src(ui_Image6, &ui_img_icon_clock_png);
lv_obj_set_width( ui_Image6, 36);
lv_obj_set_height( ui_Image6, 36);
lv_obj_set_align( ui_Image6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_Image6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image6,230);
lv_obj_set_style_border_width(ui_Image6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Image6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Image6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Image6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Image6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label20 = lv_label_create(ui_PanelTIME);
lv_obj_set_width( ui_Label20, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Label20, LV_SIZE_CONTENT);   /// 100
lv_obj_set_align( ui_Label20, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label20,"\nTIME\nLEFT          ");
lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container12 = lv_obj_create(ui_PanelTIME);
lv_obj_remove_style_all(ui_Container12);
lv_obj_set_height( ui_Container12, lv_pct(100));
lv_obj_set_flex_grow( ui_Container12, 1);
lv_obj_set_align( ui_Container12, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container12,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container12, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Screen1LabelTIMEREMAINING = lv_label_create(ui_Container12);
lv_obj_set_width( ui_Screen1LabelTIMEREMAINING, lv_pct(100));
lv_obj_set_height( ui_Screen1LabelTIMEREMAINING, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Screen1LabelTIMEREMAINING, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1LabelTIMEREMAINING,"");
lv_obj_set_style_text_color(ui_Screen1LabelTIMEREMAINING, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1LabelTIMEREMAINING, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1LabelTIMEREMAINING, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label22 = lv_label_create(ui_Container12);
lv_obj_set_width( ui_Label22, lv_pct(100));
lv_obj_set_height( ui_Label22, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label22, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label22,"HH : MM: SS");
lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label22, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label22, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label22, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label22, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelPRINTER = lv_obj_create(ui_ContainerPRINTERDATA);
lv_obj_set_width( ui_PanelPRINTER, lv_pct(100));
lv_obj_set_height( ui_PanelPRINTER, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PanelPRINTER, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelPRINTER,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PanelPRINTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_PanelPRINTER, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelPRINTER, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelPRINTER, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelPRINTER, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelPRINTER, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelPRINTER, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PanelPRINTER, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_PanelPRINTER, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PanelPRINTER, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelPRINTER, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelPRINTER, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelPRINTER, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_PanelPRINTER);
lv_obj_set_width( ui_Panel3, lv_pct(100));
lv_obj_set_flex_grow( ui_Panel3, 1);
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image7 = lv_image_create(ui_Panel3);
lv_image_set_src(ui_Image7, &ui_img_icon_printer_png);
lv_obj_set_width( ui_Image7, 24);
lv_obj_set_height( ui_Image7, 24);
lv_obj_set_align( ui_Image7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image7, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_Image7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_inner_align( ui_Image7, LV_IMAGE_ALIGN_TILE );

ui_Screen1LabelMODE = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_Screen1LabelMODE, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Screen1LabelMODE, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Screen1LabelMODE, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1LabelMODE,"IDLE");
lv_obj_set_style_text_color(ui_Screen1LabelMODE, lv_color_hex(0x00C8E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1LabelMODE, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1LabelMODE, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Container1= NULL;
ui_PanelHEADER= NULL;
ui_Label7= NULL;
ui_Panel9= NULL;
ui_Sceen1PanelSTATUS= NULL;
ui_Screen1LabelSTATUS= NULL;
ui_ContainerPRINTERDATA= NULL;
ui_PanelBEDTEMP= NULL;
ui_Image1= NULL;
ui_Label3= NULL;
ui_Container2= NULL;
ui_Container3= NULL;
ui_Screen1LabelBEDTEMPACTUAL= NULL;
ui_Screen1LabelBEDTEMPTARGET= NULL;
ui_Container4= NULL;
ui_Label1= NULL;
ui_Label6= NULL;
ui_PanelNOZZLETEMP= NULL;
ui_Image2= NULL;
ui_Label8= NULL;
ui_Container5= NULL;
ui_Container6= NULL;
ui_Screen1LabelNOZZLETEMPACTUAL= NULL;
ui_Screen1LabelNOZZLETEMPTARGET= NULL;
ui_Container7= NULL;
ui_Label11= NULL;
ui_Label12= NULL;
ui_PanelPRINTPROGRESS= NULL;
ui_Image5= NULL;
ui_Label13= NULL;
ui_Container8= NULL;
ui_Screen1BarPRINTPROGRESS= NULL;
ui_Screen1LabelPrintProgress= NULL;
ui_PanelLAYER= NULL;
ui_Image4= NULL;
ui_Label15= NULL;
ui_Container9= NULL;
ui_Container10= NULL;
ui_Screen1LabelLAYERCURRENT= NULL;
ui_Screen1LabelLAYERTOTAL= NULL;
ui_Container11= NULL;
ui_Label18= NULL;
ui_Label19= NULL;
ui_PanelTIME= NULL;
ui_Image6= NULL;
ui_Label20= NULL;
ui_Container12= NULL;
ui_Screen1LabelTIMEREMAINING= NULL;
ui_Label22= NULL;
ui_PanelPRINTER= NULL;
ui_Panel3= NULL;
ui_Image7= NULL;
ui_Screen1LabelMODE= NULL;

}
