// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: project_ui

#include "ui.h"

lv_obj_t *ui_Screen2 = NULL;lv_obj_t *ui_Container13 = NULL;lv_obj_t *ui_Image3 = NULL;lv_obj_t *ui_Screen2LabelMessage = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_event_cb(ui_Screen2, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, ui_Screen2_screen_destroy);

ui_Container13 = lv_obj_create(ui_Screen2);
lv_obj_remove_style_all(ui_Container13);
lv_obj_set_width( ui_Container13, lv_pct(100));
lv_obj_set_height( ui_Container13, lv_pct(100));
lv_obj_set_align( ui_Container13, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container13,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container13, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Container13, lv_color_hex(0x0B0F14), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Container13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container13, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container13, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image3 = lv_image_create(ui_Container13);
lv_image_set_src(ui_Image3, &ui_img_icon_3dprinter_png);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Screen2LabelMessage = lv_label_create(ui_Container13);
lv_obj_set_width( ui_Screen2LabelMessage, lv_pct(100));
lv_obj_set_height( ui_Screen2LabelMessage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Screen2LabelMessage, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen2LabelMessage,"");
lv_obj_set_style_text_color(ui_Screen2LabelMessage, lv_color_hex(0xECFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen2LabelMessage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Screen2LabelMessage, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen2LabelMessage, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Screen2LabelMessage, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Screen2LabelMessage, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Screen2LabelMessage, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Screen2LabelMessage, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Screen2_screen_destroy(void)
{
   if (ui_Screen2) lv_obj_del(ui_Screen2);

// NULL screen variables
ui_Screen2= NULL;
ui_Container13= NULL;
ui_Image3= NULL;
ui_Screen2LabelMessage= NULL;

}
