// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: project_ui

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_PanelHEADER;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Panel9;
extern lv_obj_t *ui_Sceen1PanelSTATUS;
extern lv_obj_t *ui_Screen1LabelSTATUS;
extern lv_obj_t *ui_PanelBEDTEMP;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_Screen1LabelBEDTEMPACTUAL;
extern lv_obj_t *ui_Screen1LabelBEDTEMPTARGET;
extern lv_obj_t *ui_Container4;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_PanelNOZZLETEMP;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Container5;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Container6;
extern lv_obj_t *ui_Screen1LabelNOZZLETEMPACTUAL;
extern lv_obj_t *ui_Screen1LabelNOZZLETEMPTARGET;
extern lv_obj_t *ui_Container7;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_PanelPRINTPROGRESS;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_Container8;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_Screen1BarPRINTPROGRESS;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_PanelLAYER;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Container9;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_Container10;
extern lv_obj_t *ui_Screen1LabelLAYERCURRENT;
extern lv_obj_t *ui_Screen1LabelLAYERTOTAL;
extern lv_obj_t *ui_Container11;
extern lv_obj_t *ui_Label18;
extern lv_obj_t *ui_Label19;
extern lv_obj_t *ui_PanelTIME;
extern lv_obj_t *ui_Image6;
extern lv_obj_t *ui_Container12;
extern lv_obj_t *ui_Label20;
extern lv_obj_t *ui_Screen1LabelTIMEREMAINING;
extern lv_obj_t *ui_Label22;
extern lv_obj_t *ui_PanelPRINTER;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Image7;
extern lv_obj_t *ui_Screen1LabelMODE;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

